import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import * as api from "../../services/api";
import "./ProductReviews.css";

const Stars = ({ value, interactive, onChange }) => <span className={`review-stars ${interactive ? "interactive" : ""}`} aria-label={`${value} out of 5 stars`}>{[1,2,3,4,5].map((star) => interactive ? <button key={star} type="button" aria-label={`${star} stars`} className={star <= value ? "filled" : ""} onClick={() => onChange(star)}>★</button> : <span key={star} className={star <= value ? "filled" : ""}>★</span>)}</span>;

export default function ProductReviews({ productId }) {
  const { accessToken, isAuthenticated, isAdmin } = useAuth(); const location = useLocation();
  const [reviews,setReviews]=useState([]), [mine,setMine]=useState(null), [rating,setRating]=useState(5), [reviewText,setReviewText]=useState(""), [editing,setEditing]=useState(false), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState(""), [notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [page,myReview]=await Promise.all([api.getProductReviews(productId),isAuthenticated&&!isAdmin?api.getMyProductReview(accessToken,productId).catch(()=>null):null]);setReviews(page.content||[]);setMine(myReview);}catch(e){setError(e.message);}finally{setLoading(false);}},[accessToken,isAdmin,isAuthenticated,productId]);
  useEffect(()=>{load();},[load]);
  const average=useMemo(()=>reviews.length?reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length:0,[reviews]);
  const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");setNotice("");try{const saved=mine?await api.updateReview(accessToken,mine.reviewId,{rating,reviewText}):await api.createReview(accessToken,{productId:Number(productId),rating,reviewText});setMine(saved);setReviews(current=>[saved,...current.filter(r=>r.reviewId!==saved.reviewId)]);setEditing(false);setNotice(mine?"Your review was updated.":"Thank you. Your verified review is now live.");}catch(err){setError(err.message);}finally{setSaving(false);}};
  const remove=async()=>{if(!window.confirm("Delete your review?"))return;try{await api.deleteReview(accessToken,mine.reviewId);setReviews(current=>current.filter(r=>r.reviewId!==mine.reviewId));setMine(null);setRating(5);setReviewText("");setNotice("Your review was deleted.");}catch(e){setError(e.message);}};
  const edit=()=>{setRating(mine.rating);setReviewText(mine.reviewText||"");setEditing(true);setError("");};
  return <section className="product-reviews" id="reviews"><div className="reviews-heading"><div><span>Customer perspective</span><h2>Reviews</h2></div><div className="reviews-score"><strong>{reviews.length?average.toFixed(1):"—"}</strong><div><Stars value={Math.round(average)}/><small>{reviews.length} verified {reviews.length===1?"review":"reviews"}</small></div></div></div>
    {error&&<div className="reviews-alert error" role="alert">{error}</div>}{notice&&<div className="reviews-alert success">{notice}</div>}
    {!isAuthenticated?<div className="review-callout"><h3>Purchased this frame?</h3><p>Sign in to review it after delivery.</p><Link to="/signin" state={{from:location}}>Sign in to review</Link></div>:isAdmin?<div className="review-callout"><p>Administrator accounts cannot publish customer reviews.</p></div>:mine&&!editing?<div className="my-review"><div><span>Your verified review</span><Stars value={mine.rating}/></div><p>{mine.reviewText||"Rating only"}</p><div><button onClick={edit}>Edit review</button><button className="delete" onClick={remove}>Delete</button></div></div>:<form className="review-form" onSubmit={submit}><div><label>Your rating</label><Stars value={rating} interactive onChange={setRating}/></div><label>Review <span>Optional</span><textarea value={reviewText} onChange={e=>setReviewText(e.target.value)} maxLength="2000" rows="4" placeholder="How did the frame look, feel and fit?"/></label><div className="review-form-footer"><small>Only delivered purchases can be reviewed.</small>{editing&&<button type="button" className="cancel" onClick={()=>setEditing(false)}>Cancel</button>}<button disabled={saving}>{saving?"Saving…":editing?"Update review":"Publish review"}</button></div></form>}
    <div className="reviews-list">{loading?<p className="reviews-empty">Loading reviews…</p>:reviews.length===0?<p className="reviews-empty">No reviews yet. Be the first verified customer to share your view.</p>:reviews.map(review=><article key={review.reviewId}><div className="review-avatar">{review.customerName?.charAt(0).toUpperCase()}</div><div><header><strong>{review.customerName}</strong><span>Verified purchase</span><time>{new Date(review.createdAt).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</time></header><Stars value={review.rating}/><p>{review.reviewText||"Rating only"}</p></div></article>)}</div></section>;
}
