import React, { useContext } from "react";
import "./Cart.css";
import { StoreContext } from "../../context/StoreContext";
import { useNavigate, Link } from "react-router-dom";

export default function Cart() {
  const { cartItems, product_list, removeFromCart, addToCart, getTotalCartAmount } = useContext(StoreContext);
  const navigate = useNavigate();
  const subtotal = getTotalCartAmount(); const deliveryFee = subtotal === 0 ? 0 : subtotal >= 1500 ? 0 : 99; const total = subtotal + deliveryFee;
  const lines = Object.entries(cartItems).map(([key, quantity]) => { const [productId, variantId] = key.split(":"); const product = product_list.find((item) => item._id === productId); if (!product) return null; const variant = variantId ? product.variants.find((item) => String(item.variantId) === variantId) : product.variants[0]; const image = product.images.find((item) => item.variantId === variant?.variantId) || product.images.find((item) => item.isPrimary) || product.images[0]; return { key, product, variant, quantity, image: image?.imageUrl || product.image, price: Number(variant?.price ?? product.price), color: variant?.attributes?.color || variant?.variantName || product.color }; }).filter(Boolean);
  return <div className="cart"><div className="container"><Link to="/" className="back-link">← Continue shopping</Link><h1 className="cart-title">Your bag</h1>{lines.length === 0 ? <div className="cart-empty"><p>Your bag is empty</p><Link to="/" className="cart-empty-cta">Browse eyewear</Link></div> : <div className="cart-layout"><div className="cart-items">{lines.map((line) => <div className="cart-item" key={line.key}><Link to={`/product/${line.product._id}`} className="cart-item-image"><img src={line.image} alt={line.product.name} /></Link><div className="cart-item-info"><Link to={`/product/${line.product._id}`}><p className="cart-item-name">{line.product.name}</p></Link><p className="cart-item-color">{line.color}{line.variant?.sku && ` · ${line.variant.sku}`}</p><p className="cart-item-price">₹{line.price.toLocaleString("en-IN")}</p></div><div className="cart-item-qty"><button onClick={() => removeFromCart(line.product._id, line.variant?.variantId)}>−</button><span>{line.quantity}</span><button disabled={line.quantity >= Number(line.variant?.quantityAvailable || Infinity)} onClick={() => addToCart(line.product._id, line.variant?.variantId)}>+</button></div><p className="cart-item-total">₹{(line.price * line.quantity).toLocaleString("en-IN")}</p><button className="cart-item-remove" onClick={() => { for (let index = 0; index < line.quantity; index += 1) removeFromCart(line.product._id, line.variant?.variantId); }} aria-label={`Remove ${line.product.name} ${line.color}`}>×</button></div>)}</div><div className="cart-summary"><h2>Order summary</h2><div className="cart-summary-row"><span>Subtotal</span><span>₹{subtotal.toLocaleString("en-IN")}</span></div><div className="cart-summary-row"><span>Shipping</span><span>{deliveryFee === 0 ? "Free" : `₹${deliveryFee}`}</span></div>{deliveryFee > 0 && <p className="cart-free-ship-hint">Add ₹{(1500 - subtotal).toLocaleString("en-IN")} more for free shipping</p>}<div className="cart-summary-divider" /><div className="cart-summary-row cart-summary-total"><span>Total</span><span>₹{total.toLocaleString("en-IN")}</span></div><button className="cart-checkout-btn" onClick={() => navigate("/order")}>Proceed to checkout</button><div className="cart-promo"><input type="text" placeholder="Promo code" /><button>Apply</button></div></div></div>}</div></div>;
}
